import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export function InvestmentMemo() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between border-b pb-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-gray-900">Investment Memo</h1>
          <p className="text-gray-500 mt-1">Acme Corp due diligence generated by VentureLens AI</p>
        </div>
        <div className="mt-4 sm:mt-0 flex items-center space-x-2 bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium">
          <span className="w-2 h-2 rounded-full bg-green-500"></span>
          <span>Strong Buy Recommendation</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Risk Scores */}
        <Card className="col-span-1 md:col-span-1">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">AI Confidence Scores</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-gray-700">Financial Health</span>
                <span className="text-green-600 font-bold">85/100</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div className="bg-green-500 h-2 rounded-full" style={{ width: '85%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-gray-700">Founder Assessment</span>
                <span className="text-blue-600 font-bold">92/100</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div className="bg-blue-500 h-2 rounded-full" style={{ width: '92%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-gray-700">Market Opportunity</span>
                <span className="text-yellow-600 font-bold">75/100</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2">
                <div className="bg-yellow-500 h-2 rounded-full" style={{ width: '75%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-gray-700">Legal Risk Profile</span>
                <span className="text-green-600 font-bold">Low Risk</span>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Investment Thesis */}
        <Card className="col-span-1 md:col-span-2">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Investment Thesis</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none text-gray-600">
            <h4 className="text-gray-900 font-semibold mb-1">Bull Case</h4>
            <p className="mb-3">
              Acme Corp has demonstrated exceptional unit economics with an LTV:CAC ratio of 4.5 and a net revenue retention (NRR) of 130%. 
              If they capture 5% of their $10B TAM, they can reach $500M ARR within 5 years, positioning them for a strong IPO.
            </p>
            
            <h4 className="text-gray-900 font-semibold mb-1">Bear Case</h4>
            <p>
              Increased competition from legacy incumbents could drive CAC up by 40%. 
              If their product roadmap is delayed, customer churn could increase, extending their payback period beyond 18 months and requiring an emergency bridge round.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
