import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function InvestmentMemo() {
  return (
    <div className="space-y-6 text-slate-100">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between border-b border-slate-800 pb-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-slate-100">Investment Memo</h2>
          <p className="text-slate-400 mt-1">Acme Corp due diligence generated by VentureLens AI</p>
        </div>
        <div className="mt-4 sm:mt-0 flex items-center space-x-2 bg-emerald-950/50 text-emerald-400 border border-emerald-500/30 px-3 py-1 rounded-full text-sm font-medium">
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
          <span>Strong Buy Recommendation</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Risk Scores */}
        <Card className="col-span-1 md:col-span-1 bg-slate-900 border-slate-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg text-slate-200">AI Confidence Scores</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-slate-300">Financial Health</span>
                <span className="text-emerald-400 font-bold">85/100</span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-2">
                <div className="bg-emerald-500 h-2 rounded-full" style={{ width: '85%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-slate-300">Founder Assessment</span>
                <span className="text-blue-400 font-bold">92/100</span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-2">
                <div className="bg-blue-500 h-2 rounded-full" style={{ width: '92%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-slate-300">Market Opportunity</span>
                <span className="text-amber-400 font-bold">75/100</span>
              </div>
              <div className="w-full bg-slate-800 rounded-full h-2">
                <div className="bg-amber-500 h-2 rounded-full" style={{ width: '75%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1">
                <span className="font-medium text-slate-300">Legal Risk Profile</span>
                <span className="text-emerald-400 font-bold">Low Risk</span>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Investment Thesis */}
        <Card className="col-span-1 md:col-span-2 bg-slate-900 border-slate-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg text-slate-200">Investment Thesis</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-slate-300 text-sm">
            <div>
              <h4 className="text-slate-100 font-semibold mb-1">Bull Case</h4>
              <p className="leading-relaxed">
                Acme Corp has demonstrated exceptional unit economics with an LTV:CAC ratio of 4.5 and a net revenue retention (NRR) of 130%. 
                If they capture 5% of their $10B TAM, they can reach $500M ARR within 5 years, positioning them for a strong IPO.
              </p>
            </div>
            
            <div>
              <h4 className="text-slate-100 font-semibold mb-1">Bear Case</h4>
              <p className="leading-relaxed">
                Increased competition from legacy incumbents could drive CAC up by 40%. 
                If their product roadmap is delayed, customer churn could increase, extending their payback period beyond 18 months and requiring an emergency bridge round.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
