"use client";

import React from "react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api-client";
import { AlertTriangle, AlertOctagon, Info, ShieldCheck } from "lucide-react";

type Alert = {
  id: string;
  title: string;
  company: string;
  score: string;
  severity: "High" | "Medium" | "Low";
  time: string;
};

export default function AlertsView() {
  const { data: alerts = [], isLoading } = useQuery<Alert[]>({
    queryKey: ["alerts"],
    queryFn: async () => {
      const res = await apiClient.get("/api/v1/alerts");
      return res.data;
    }
  });

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-white">Risk Alerts & Notifications</h2>
        <p className="text-xs text-slate-400 mt-0.5">Real-time alerts generated by automated background audit workers.</p>
      </div>

      {isLoading ? (
        <div className="text-center text-slate-400 text-xs py-8">Loading active alerts...</div>
      ) : alerts.length === 0 ? (
        <div className="bg-[#0b0e14] border border-[#161c28] p-8 rounded-xl text-center flex flex-col items-center justify-center space-y-2">
          <ShieldCheck className="w-10 h-10 text-emerald-400" />
          <span className="text-xs text-slate-400">All portfolio companies operating within normal boundaries. No active risk logs.</span>
        </div>
      ) : (
        <div className="space-y-3">
          {alerts.map((alert) => (
            <div
              key={alert.id}
              className={`p-4 rounded-xl border flex items-start space-x-4 shadow-sm transition-all hover:bg-[#0f1421]/20 ${
                alert.severity === "High"
                  ? "bg-red-950/15 border-red-500/25 text-slate-200"
                  : alert.severity === "Medium"
                  ? "bg-amber-950/15 border-amber-500/25 text-slate-200"
                  : "bg-slate-900/40 border-slate-800 text-slate-300"
              }`}
            >
              <div className="mt-0.5 shrink-0">
                {alert.severity === "High" ? (
                  <AlertOctagon className="w-5 h-5 text-red-400" />
                ) : alert.severity === "Medium" ? (
                  <AlertTriangle className="w-5 h-5 text-amber-400" />
                ) : (
                  <Info className="w-5 h-5 text-blue-400" />
                )}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex justify-between items-center flex-wrap gap-2">
                  <h4 className="text-xs font-bold text-slate-100">{alert.title}</h4>
                  <span className="text-[9px] text-slate-500">{alert.time}</span>
                </div>
                <p className="text-[10px] text-slate-400 mt-1">
                  Startup Impact: <strong className="text-slate-200">{alert.company}</strong>
                </p>
                <div className="flex items-center space-x-2 mt-2">
                  <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded ${
                    alert.severity === "High" 
                      ? "bg-red-500/10 text-red-400" 
                      : alert.severity === "Medium"
                      ? "bg-amber-500/10 text-amber-400"
                      : "bg-blue-500/10 text-blue-400"
                  }`}>
                    {alert.severity} Risk
                  </span>
                  <span className="text-[9px] text-slate-500">{alert.score}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
