apiVersion: v1
kind: Service
metadata:
  name: venturelens-api-svc
  namespace: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: venturelens-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
